# https://github.com/elias-2001-de/jonah
git_base = "https://github.com/elias-2001-de/"

[[projects]]
git_rel = "oberon0c"
build_file = "jonah_editor.toml"
out_path = "en/projects/"

[[projects]]
git_rel = "open-gal"
build_file = "jonah_editor.toml"
out_path = "en/projects/"

[[projects]]
git_rel = "func-checker"
build_file = "jonah.toml"
out_path = "en/projects/"
