
image = "/images/portrait.webp"

[title]
en = "My Journey in Tech"
de = "Entwicklung von Systemen Mein Profil als Softwareentwickler"

[content]
en = [
    [
        "Hi, I'm Elias Maier, a software developer based in Konstanz, Germany. I specialize in systems programming and web development, ",
        "combining both through WebAssembly. My interest in technology began at an early age, and over the years, I have worked on various ",
        "interesting projects, including complex APIs, Compilers, stereo cameras, and robot swarms.",
    ],
    [
        "My programming journey started in secondary school when I was first introduced to Delphi ",
        "in a programming course. This ignited my passion and led me to attend a specialized high school ",
        "focused on informatics. I learned C and Assembly there and even co-developed my own hardware ",
        "description language, EasyGAL, as a school project. After graduating, I began studying Computer ",
        "Science at the University of Konstanz, where I am completing my bachelor's degree. My thesis focuses on ",
        "classifying robot swarm behaviors using autoencoders and analyzing large-scale simulations of autonomous robots.",
    ],
    [

        "In addition to my studies, I have gained practical experience through various professional roles. ",
        "During a six-month internship at Storz Medical, I developed a prototype for a stereo camera tracking system ",
        "for medical applications, focusing on software architecture and real-time data processing. Before that, I worked ",
        "at Studiswork. In this startup, I was responsible for the backend infrastructure, integrating Express.js with a Svelte ",
        "frontend and developing a user authentication and worker management system from scratch. After my internship, I joined ",
        "Okworx, a company specializing in environmental data processing, where I contributed to backend development and system architecture.",
    ],
]

de = [
    [
        "Hallo, ich bin Elias Maier, Softwareentwickler aus Konstanz, Deutschland. ",
        "Mein Schwerpunkt liegt auf der Systemprogrammierung und Webentwicklung,ich kombirire ",
        "beide bereiche durch WebAssembly. Schon früh entdeckte ich meine Begeisterung für Informatik ",
        "und habe seither an vielseitigen Projekten gearbeitet von komplexen APIs über Compiler ",
        "bis hin zu Stereokameras und Roboterschwärmen.",
    ],
    [
        "Meine ersten Programmiererfahrungen sammelte ich in der Realschule durch einen freiwilligen Kurs, ",
        "der mein Interesse an Informatik weckte. Anschließend besuchte ich ein Technisches Gymnasium, ",
        "wo ich neben Softwarearchitektur und UML-Diagrammen auch hardwarenahe Programmierung mit ",
        "C und Assembler erlernte. Gemeinsam mit einem Mitschüler entwickelte ich als Schulprojekt ",
        "die Hardware-Beschreibungssprache EasyGAL. Nach dem Abitur begann ich mein Informatikstudium an ",
        "der Universität Konstanz, wo ich derzeit meinen Bachelor abschließe. In meiner Abschlussarbeit beschäftige ",
        "ich mich mit der Klassifizierung des Verhaltens von Roboterschwärmen mittels Autoencodern sowie der ",
        "Analyse großer Simulationen autonomer Roboter.",
    ],
    [

        "Neben dem Studium konnte ich durch verschiedene Nebenjobs praktische Erfahrung sammeln. ",
        "Mein erster Job war als Werkstudent an der Universität Konstanz, wo ich vor allem mit der ",
        "Entwicklung von APIs betraut war. Danach wurde ich von Studiswork, einem Startup, beauftragt, ",
        "die Firmenwebsite zu entwickeln. Dort war ich für die Backend-Infrastruktur verantwortlich, ",
        "integrierte Express.js mit einem Svelte-Frontend und entwickelte ein Authentifizierungs- sowie ein ",
        "Mitarbeiterverwaltungssystem von Grund auf. Während eines sechsmonatigen Praktikums bei Storz Medical ",
        "arbeitete ich an einem Prototyp für ein Stereo-Kamera-Tracking-System. Nach dem Praktikum wechselte ",
        "ich zu Okworx, einem Unternehmen, das sich auf die Verarbeitung von Umweltdaten spezialisiert hat, ",
        "wo ich an der Backend-Entwicklung und der Systemarchitektur mitwirkte.",
    ],
    [

        "Diese Erfahrungen haben meine Fähigkeiten sowohl in der Softwareentwicklung als ",
        "auch in der Systemarchitektur geschärft und mich gelehrt, komplexe technische ",
        "Herausforderungen effizient zu lösen.",
    ],

]
