[title]
en = "Writing on software engineering, embedded systems, and system design."
de = "Schreiben über Softwareentwicklung, Embedded-Systeme und Systemdesign."

[intro]
en = "A collection of my thoughts on programming, system architecture, hardware-software interaction, and open-source development—organized chronologically."
de = "Eine Sammlung meiner Gedanken zu Programmierung, Systemarchitektur, der Interaktion zwischen Hardware und Software sowie Open-Source-Entwicklung  chronologisch geordnet."
