
[title]
en = "Things I've made from Compilers to Web Apps."
de = "Meine Projekte von Compilern zu Webanwendungen."


[intro]
en = [
    "I have worked on various projects, ranging from ",
    "compilers to web applications, with a strong interest ",
    "in low-level programming and the web. Some projects were developed ",
    "on my own, while others were collaborative efforts. I enjoy exploring the potential ",
    "of WebAssembly. These projects are interactive and can be tried directly in the browser, with no downloads required.",
]
de = [
    "Ich habe an verschiedenen Projekten gearbeitet, die von Compilern bis hin zu Web apps reichen, ",
    "wobei ich ein starkes Interesse an Low-Level-Programmierung und dem Web habe. ",
    "Einige Projekte habe ich selbst entwickelt, an anderen habe ich mitgearbeitet. ",
    "Es macht mir Spaß, das Potenzial von WebAssembly zu erforschen. ",
    "Diese Projekte sind interaktiv und können direkt im Browser ausprobiert werden, ohne dass Downloads erforderlich sind.",
]

[[projects]]
description = { en = "An app for Mainau garden Island with features like ticket booking and user chat.", de = "Eine App für die Insel Mainau mit Funktionen wie Ticketbuchung und Nutzer-Chat." }
name = { en = "Island Explorer", de = "Insel Exporer" }
link = "island-explorer"
logo = "/images/logos/Mainau_logo.svg"
repo = "https://github.com/elias-2001-de/island-explorer"


[[projects]]
name = { en = "Oberon0c", de = "Oberon0c" }
description = { en = "An Oberon-0 compiler that runs in the browser using WASM", de = "Ein Oberon-0-Compiler, der im Browser mit WASM läuft." }
link = "oberon0c"
logo = "/images/logos/Oberon.png"
repo = "https://github.com/elias-2001-de/oberon0c"

[[projects]]
description = { en = "A hardware description language (HDL) designed for Generic Array Logic (GAL) chips.", de = "Eine Hardware-Beschreibungssprache (HDL) für Generic-Array-Logic (GAL) Chips." }
name = { en = "Open-gal", de = "Open-gal" }
link = "open-gal"
logo = "/images/logos/microchip.png"
repo = "https://github.com/elias-2001-de/open-gal"


[[projects]]
description = { en = "compares Boolean functions and shows their truth tables.", de = "vergleicht Boolesche Funktionen und zeigt die Wahrheitstabelle." }
name = { en = "Boolean Function Checker", de = "Boolean Function Checker " }
link = "func-checker"
logo = "/images/logos/table.png"
repo = "https://github.com/elias-2001-de/func-checker"
